server {
    listen 80;
    server_name api.liquest.click;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.liquest.click;

    ssl_certificate /etc/letsencrypt/live/api.liquest.click/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.liquest.click/privkey.pem;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
	proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
